# Generated by Django 3.2.9 on 2021-12-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
    ]
